config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_in'=> 'devise/sessions#new'
  end

  root 'challenges#index'

  resources :challenges

  get '/users/:id', to: 'users#show', as: "user"

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
    
    has_many :challenges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
 	end

end

app/controllers/challenges_controller.rb
require 'hacker_rank_client'
class ChallengesController < ApplicationController
   before_filter :authenticate_user!

	def index
		@challenges = Challenge.all.reverse_order()
	end

	def create
		@challenge = Challenge.new(challenge_params)
		@challenge.user = current_user
		if @challenge.save
			redirect_to root_url
		end
	end

	def show
		@challenge = Challenge.find(params[:id])
	end

	def new
		@challenge = Challenge.new
	end


	def destroy
		@challenge = Challenge.find(params[:id])
		@challenge.destroy
		redirect_to root_url
	end

	def update
		client = HackerRankClient.new
    	response = client.submit_code(params[:challenge]["body"], "5", '["1\n"]')
		message = (response.handled_response[:message])
		flash[:notice] = message
		redirect_to root_url
	end

	private
	def challenge_params
		params.require(:challenge).permit(:user_id, :title, :body, :language, :description, :answer)
	end
end

app/controllers/hacker_rank_controller.rb
class HackerRankController < ApplicationController
  def index
  end

  def submit_code(source, language_number,test_cases)
    client = HackerRankClient.new
    response = client.submit_code(source, language_number,test_cases)

    respond_to do |format|
      format.json { response }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/hacker_rank_helper.rb
module HackerRankHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenges/index.html.erb
<title> Ada </title>
<div class="container">
	<div class="search-bar">
		<%= link_to "New Challenge", new_challenge_path, class: "btn btn-success"%>
	</div>
    <hr>

        <% @challenges.each do |challenge| %>
            <div class="opening" >
                <h3 class=""><%= link_to challenge.title, challenge %></h3> <%= link_to "#{challenge.user.name}", challenge.user %>
                <div class="jumbotron">
                    <p class=""><%= challenge.description %></p>
                    <p class=""> Language: <%= challenge.language %></p>
                    <% if challenge.user == current_user %>
                        <%= link_to "Delete", challenge, method: :delete, class: "btn btn-default" %>
                    <% end %>
                </div>
            </div>
        <% end %>

</div>

app/views/challenges/new.html.erb
<title> New Challenge</title>
<%= form_for @challenge do |f| %>
	<div class="jumbotron" style="position:relative; margin-bottom:-30px;">
		<h2 align ='middle'>New Challenge </h2>
		<div class="title">
			<%= f.label :title, class: "label-name" %>
			<%= f.text_field :title, class: 'form-control'  %>
		</div>
		<div class="description">
			<%= f.label :description, class: "label-name" %>
			<%= f.text_area :description, size: "60x10", class: 'form-control' %>
		</div>

      <div class="language">
        <%= f.label :answer, class: "label-name" %>
        <%= f.text_field :answer, class: "form-control"  %>
      </div>

		<div class="language">
			<%= f.label :language, class: "label-name" %>
			<%= f.text_field :language, class: "form-control"  %>
		</div>
		<div>
			<%= f.submit "Create Challenge", class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/challenges/show.html.erb
<title> <%=@challenge.title %></title>

<div class="challenge-header">
	<h1 align ='middle'><%= @challenge.title %></h1>
    <h4 align="middle"><%= link_to "#{@challenge.user.name}", @challenge.user%> </h4>
    <p align="middle"><%= @challenge.description %> <strong><%=@challenge.language  %></strong></p>
</div>
    <% if @challenge.body.nil? %>
        <%= form_for @challenge do |c| %>
            <div>
                <%= c.text_area :body, size:"60x20", class: "form-control"  %>
            </div>

            <div>
                <%= c.submit "Submit!", class: "btn btn-primary", style: "position:relative; margin-bottom: 30px;" %>
            </div>
        <% end %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="notice" style="display:none">
      <p id="message"> <%= flash.now[:notice] %></p>
    </div>

    <div class="icon">
		<%= link_to image_tag("/ada_logo.png", size: "238x100"), root_url %>
	</div>
	<div class="top-bar-right">
		<img src="/top_bar_right2.png" height="100" width="279.25"/>
	</div>
	<div class="top-bar-middle">
	</div>
    <% if user_signed_in? %>
		<div class="container">
			<ul class="nav nav-tabs">
              <li role="presentation"> <%=link_to "#{current_user.name}", current_user %> </li>
			  <li role="presentation"> <%= link_to "Home", root_url %></li>
			  <li role="presentation"> <%= link_to "Account", edit_user_registration_path %></li>
			  <li role="presentation"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
			  </li>
			</ul>
	    </div>
    <% end %>

<%= yield %>

</body>
</html>


<script>
    $(function(){
        var text = $(".notice #message").text().trim();
        if (!!text) {
            $(".notice").fadeIn("slow");
            $(".notice").fadeOut(15000);
        }
    });
</script>

app/views/users/show.html.erb
<title> <%=@user.name %></title>
<div class="container">
      <div class="search-bar">
        <%= link_to "New Challenge", new_challenge_path, class: "btn btn-success" %>
      </div>
      <hr>


    <% @user.challenges.each do |challenge| %>
        <div class="opening" >
          <h3 class=""><%= link_to challenge.title, challenge %></h3> <%= link_to "#{challenge.user.name}", challenge.user %>
          <div class="jumbotron">
            <p class=""><%= challenge.description %></p>
            <p class=""> Language: <%= challenge.language %></p>
            <% if current_user == challenge.user %>
                <%= link_to "Delete", challenge, method: :delete, class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
    <% end %>
</div>